# Ways of Knowing: Integrating Humanity into your Teaching

## Overview {.unnumbered}

In this unit, we will consider how to create authentic learning spaces that invite, support, and honour a wide range of ways of knowing. In our undergraduate and graduate programs, Trinity Western University has developed a curriculum based on the foundational idea that humans learn and know in different ways. We know, for example, that there are some things we will know through scientific investigation – the same way that we understand that there are some things we may know best through art or poetry. If you want to know more about TWU Ways of Knowing, explore Core Ways of Knowing (TWU, n.d.)

As you approach your role as teacher, facilitator, or coach, you may find that it is helpful to design learning experiences with these ways of knowing in mind.

Unit 7 focuses on two guiding questions:

- How can we incorporate diverse ways of knowing into the learning communities we create?
- How can I support student motivation?

### Topics {.unnumbered}

This unit is divided into the following topics:

1. Ways of Knowing
2. The Adult Educator as Servant Leaders

### Unit Learning Outcomes {.unnumbered}

When you have completed this unit, you will be able to:

- create a learning experience that integrates diverse ways of knowing.
- design learning experiences that support learner motivation.

### Learning Activities {.unnumbered}

Here is a list of learning activities that will benefit you in completing this unit. You may find it useful for planning your work.

::: {.learning-activity}

- Design an in-class learning experience or assignment that integrates one of TWU's Core Ways of Knowing.
- Watch "Servant Leadership: How a Jar Can Change the Way You Lead and Serve" (TEDx Talks, 2017) and share your reflections in the learning community.

*Note:* Working through learning activities will help you to meet the learning outcomes and successfully complete your assessments.
:::

### Assessment {.unnumbered}

See the Assessment section in Moodle for assignment details.

### Resources {.unnumbered}

Here are the resources you will need to complete this unit.

- Wheatly, M. (2023). [*Who do we choose to be?, Second edition: Facing reality, claiming leadership, restoring sanity.*](https://research-ebsco-com.twu.idm.oclc.org/linkprocessor/plink?id=eeef8a8d-c136-3ca8-ac5e-941498abb4ce){target="_blank"} Berrett-Koehler Publishers.
- Other online resources will be provided in the unit.

## Ways of Knowing

As we consider how to create authentic learning experiences, it is essential that we keep in mind that we are teaching people—not content. The learners we interact with show up to their learning experiences as whole people—and thus, we must create learning experiences that engage a wide diversity of ways of knowing.

As multi-dimensional human beings, we learn in many ways. We learn through language and culture, through art and music, through scientific investigation and writing and listening. Trinity Western University designs the undergraduate core curriculum around this foundational concept: that we know in different ways. In Western culture, we often prioritize certain ways of knowing over others. For example, we may believe that something learned through the scientific method over something communicated through aesthetic performance.

Many of us are aware of the ways of knowing prioritized in traditional Western education. These can be found in TWU’s core foundations and include: academic research and writing, logical and ethical reasoning, and scientific method and lab research. With a focus on Christian liberal arts education, TWU has also included religious and spiritual thought, as well as foundations courses focused on Christian liberal arts, human flourishing, and ideas that inspire.

In addition to these foundational courses, additional ways of knowing outlined by Trinity include: aesthetic and performance, cultural and linguistic, experienced and embodied, historical and archival, quantitative and computational, and social and global.

By designing learning experiences that embed different ways of knowing, we acknowledge the full diversity of the human experience. For example, courses that integrate aesthetic knowing allow us to understand that the world around us is not fully knowable through rational thought and pragmatic analysis. For example, how does one truly know love? Or grief? Or complexity?

TWU describes this way of knowing as follows:

> Aesthetic and performance inquiry demonstrate to students that some forms of knowledge are best understood through intuitive, imaginative, creative, and interpretive methodologies in which makers and receivers come to insight and understanding. It affirms that the ability to understand and discern the world around us and our place within it is conditioned not only by the intellect, but also by the senses—the science of sensory knowledge and the appreciation of the beautiful playing a critical role in human experience. It teaches students that the aesthetic dimension of life ensures meaning and value in ways distinct from rationalism, pragmatism, and mechanism. Experiencing and reflecting on an art form cultivates abilities that can enhance and be valuably applied to other ways of learning and modes of inquiry. (TWU, n.d.)

### Activity: Core Ways of Knowing

::: {.learning-activity time="30"}

Review the ["Core Ways of Knowing"](https://www.twu.ca/about-us/liberal-arts-core/core-ways-knowing){target="_blank"} (TWU, n.d.). Choose one of the six ways of knowing that interests you. Design an in-class learning experience or assignment that would allow you to integrate this way of knowing. As you write the instructions for the learning experience or assignment, be as specific as possible. Add enough details that someone else could pick up your instructions and facilitate that learning experience.

*Note:* This learning activity will help you prepare for the next assignment.

:::

#### Beyond Scientific Reasoning {.unnumbered}

By expanding our learning experiences to include diverse ways of knowing, we can not only deepen student engagement, but also deepen student learning. After all, perception based on scientific understanding is not the only way of knowing. Wheatley (2017) admonishes, "There are other ways of knowing reality, reliable methods that have served humans and earlier hominids for millennia. It is the arrogance of our science that denies their existence and their usefulness" (p. 179).

Beyond the conceptual idea of ways of knowing, it is important to consider howe we, as adult educators can incorporate other ways of knowing into the learning experiences we design.

Cahalan (2016) has identified eight ways of knowing that are essential to wise practice:

- Situated awareness is noticing and describing contextual factors.
- Embodied realizing is developing skilled competence in bodily action.
- Conceptual understanding is comprehending and remembering key information.
- Critical thinking is analyzing and evaluating concepts and actions.
- Emotional attunement is identifying and using awareness of feelings and affective states.
- Creative insight is developing imaginative and creative responses.
- Spiritual discernment is perceiving what is of God and not of God.
- Practical reasoning is problem-solving, forming judgments, gaining a sense of salience, and acting wisely.

These ways of knowing are another way to consider the process and experience of learning, beyond simply reading and writing. An assignment that incorporates music, for example, might allows students to experience *emotional attunement.* An assignment that asks a student to create learning activities that focus on ways of knowing (as you are being asked to do in this course), might require the student to use creative insight and imagination.

As an education, when you choose texts, articles, music, or poems, this determines the extent to which students experience the full range of knowing in their learning. The resources you select also determine the type of information students pay attention to.

Embodied realizing in the classroom may take the form of an experiential learning activity where the students are asked to interview someone, ‘shadow’ them for a time or listen to a podcast and describe their ‘gut reactions’ or impressions. Reading biographies is an excellent way for learners to become more emotionally attuned to the feelings and affective states of others. This develops empathy—a crucial component of being hospitable in a diverse, pluralistic society.

## The Adult Educator as Servant Leader

Servant leadership requires a strong orientation to values that allow adult educators to know, care about, and serve their learners well. Since beliefs, influenced by context and culture influence decision making, expectations and emotions, it matters greatly what leadership model you adhere and aspire to. What we value, we prioritize and this shapes our work and lives.

By way of example of what servant leadership can look like as an adult educator, I share part of my own journey with you. As a Canadian educator, one key challenge I face is the mandate to Indigenize the curriculum. This is part of a broader call to educational leaders to work toward healing and reconciliation. In Canadian history, education was used as a tool of assimilation to extricate children from their culture and language. A statement of the Aboriginal Healing Foundation (2010) succinctly summarizes the gravity of this call to action:

> No other population group in Canada’s history has endured such a deliberate, comprehensive, and prolonged assault on their human rights as that of Indigenous people. Yet, despite growing recognition of past wrongs, many Canadians remain unaware of the full scope of these injustices or their impacts. (p. 35).
>
> Dr. Adrienne Castellon, an original author of this course, shared her reflections on the process of learning about and integration Indigenous perspectives into her teaching and learning.
>
> More than a political mandate however, educators need to realize our moral responsibilities to relate accurately and acknowledge fully the nation’s regrettable past. I propose that the effort educators in Canada are undergoing requires servant leadership dispositions. For me, this has been, and continues to be, a process of developing knowledge of my own ignorance, discovering my own prejudices and myths and having the courage to change views and practices. It has required the disposition to work through intellectual and emotional complexities that have caused confusion and frustration. But I am willing to be disturbed and unsettled. As I strive to live servant leadership principles, approach this challenge with intellectual humility, curiosity and respect for all people which has taken much of the fear of ‘doing it wrong’ away. (Castellon, n.d.)

Our world is in need of adult educators who strive to live servant leadership principles in their practice. The resulting wideness of spirit dedicated toward the welfare of others is magnanimity—what Aristotle called the crowing virtue in his hierarchy of virtues. The adult educator has an important role in creating a more peaceful world through education that serves people and influences others to do the same.

For more information about servant leadership, please see the resource section for this unit.

### Activity: Servant Leadership Video

::: {.learning-activity time="30"}

Watch ["Servant Leadership: How a Jar Can Change the Way You Lead and Serve"](https://www.youtube.com/watch?v=1vIPrR_clEg){target="_blank"} (TEDx Talks, 2017). As you watch the video, consider how assumption and perceptions may impact your role as an adult educator? How are adult educators servant leaders?

::: video-container
{{< video https://www.youtube-nocookie.com/embed/1vIPrR_clEg >}}
:::

**Questions to Consider:**

- How are you going to live out the seven concepts of intentional practice Frett outlines? List each of the concepts and how you could live each one.
- Reference the Brookfield and Preskill (2016) and Silberman and Biech (2015) and find one (1) strategy to apply to each of the seven (7) concepts. List each concept of intentional practice and your chosen strategy beside it, include a brief description of the strategy.
- In a general manner, explain how to use the strategies with intentionality to be a servant leader in the adult learning environment.

*Note:* This activity serves as the discussion prompt for this unit. Share your response and connect with others in the Learning Community to deepen your understanding.

:::

## Summary {.unnumbered}

In this unit, you have had the opportunity to learn about the role of information and perception in growth and development. You explored the role of adult educator to be an advocate for adult learners. Hopefully the term ‘warrior for the human spirit’ is a compelling call to action for you as a result.

You also explored the concept of the adult educator as servant leader and the importance of intentional practice based on this model of leadership. An adult educator who acts and interacts for the good of learners brings meaning to work and can motivate learners to also find meaning beyond an instrumental, skills-focused view of education. This can lead to a sense of fulfillment and flourishing built on a greater purpose.

::: check

Before you move on to the next unit, you may want to check to make sure that you are able to:

- choose and/or design strategies with a critical lens for using information to influence growth and development of learners.
- explain how an adult educator can be a servant leader.

:::

## References {.unnumbered}

Trinity Western University. (n.d.). *Core ways of knowing.* [https://www.twu.ca/about-us/liberal-arts-core/core-ways-knowing](https://www.twu.ca/about-us/liberal-arts-core/core-ways-knowing){target="_blank"}

Aboriginal Healing Foundation (2010). *A compendium of Aboriginal Healing Foundation research.* Dollco Printing. [https://ehprnh2mwo3.exactdn.com/wp-content/uploads/2021/01/research-compendium.pdf](https://ehprnh2mwo3.exactdn.com/wp-content/uploads/2021/01/research-compendium.pdf){target="_blank"}

Brookfield, S. and Preskill, S. (2016). *The discussion book: 50 great ways to get people talking.* Jossey Bass.

Silberman, M. L., & Biech, E. (2015). *Active training: A handbook of techniques, designs, case examples, and tips* (4th ed.). Wiley.
